spring.application.name=DevGuide

# MyBatis, DB
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;IFEXISTS=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
# log4jdbc ?? ??
spring.datasource.url=jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;IFEXISTS=FALSE
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.username=sa
spring.datasource.password=

log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.dump.sql.maxlinelength=0

spring.sql.init.mode=always
spring.h2.console.enabled=true

logging.config=classpath:logback.xml

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.config-location=classpath:/config/mybatis.xml
mybatis.type-aliases-package=com.lgsurvey.DevGuide.dto

pagehelper.helper-dialect= h2

# server

server.port:8080
server.tomcat.relaxed-query-chars=|,{,},[,],^

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=1000MB
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-query-params-without-oauth2=true
springdoc.swagger-ui.doc-expansion=none

# 6000 : 100?
# 86400 : 24 ??
jwt.accessToken.expiration_time=6000
jwt.refreshToken.expiration_time=86400

#jwt.accessToken.expiration_time=60
#jwt.refreshToken.expiration_time=120
jwt.secret=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# app 커스텀 속성
app.sso-url=https://www.naver.com
app.file.rootPath=C:\\data\\uploads
#app.file.rootPath=/Users/yongsungahn/data
#app.file.rootPath=/Users/yongsungahn/data
